<a href="https://colab.research.google.com/github/odinokov7/numpy-pandas/blob/main/hw_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
aT = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
aT

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [ ]:
a = aT.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
mean_a = np.mean(a, axis= 0)
mean_a

array([2. , 8.4])

In [ ]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [ ]:
a1 = a_centered[:, 0]
a2 = a_centered[:, 1]
a_centered_sp = np.dot(a1, a2)
a_centered_sp

8.0

In [ ]:
N = a.shape[0]
N

5

In [ ]:
b = a_centered_sp / (N - 1)
b

2.0

In [ ]:
import pandas as pd

In [ ]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                   'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [ ]:
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     'price':[450, 300, 350, 500, 450, 370, 290]}, 
                      columns=['author_id', 'book_title', 'price'])
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [ ]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [ ]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [ ]:
col1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns = {'price':'min_price'})
col2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns = {'price':'max_price'})
col3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns = {'price':'mean_price'})
authors_stat = pd.concat([col1, col2, col3], axis = 1)
authors_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000